INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Ricardo Luiz de Almeida', 'São José dos Campos', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('José Fransico Xavier', 'São José dos Campos', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Alberto da Silva', 'São José dos Campos', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Aline Silveira da Cunha', 'São José dos Campos', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Ricardo Oliveira e Silva', 'São José dos Campos', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Luiz de Andrade', 'São José dos Campos', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Luiz da Silva Junior', 'Jacaréi', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Silvio Luiz', 'Jacaréi', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Ronaldo de Andrade', 'Jacaréi', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('José Silva', 'Jacaréi', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('José Luiz', 'Jacaréi', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Osvaldo da Cunha', 'Caçapava', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Arnaldo Oliveira', 'Caçapava', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Fransisco Junior', 'Taubaté', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Fransica Oliveira Cunha', 'Taubaté', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Camila de Andrade e Silva', 'Caçapava', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Carlos Munhos', 'Caçapava', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Fabiana Oliveira', 'São Paulo', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('Ricardo Oliveira', 'São Paulo', 'SP');
INSERT INTO tbClientes(Nome, Cidade, UF) VALUES ('José Camilo', 'São Paulo', 'SP');